#!/bin/bash
docker rm -f jenkins
docker run --name jenkins -d -p 8080:8080 --volumes-from=jenkins-mvn-cache --volumes-from=jenkins-jobs --volumes-from=jenkins-config -u root -e JENKINS_HOME=/data/jenkins -e NEXUS_HOST=http://10.117.105.140:8081 10.117.105.140:5000/shareinto/jenkins:0.1
